---
title: "Speeding-up-science-metatranscriptomics-taxa-summary"
author: "Zeya Xue"
date: "5/9/2019"
output: rmarkdown::github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(fig.path = "figs/")
```

## Load packages and setting up
```{r}
library(phyloseq);packageVersion("phyloseq")
library(DESeq2);packageVersion("DESeq2")
library(ggplot2)
library(reshape2)
library(superheat)
library(plyr)
library(dplyr)
```

## Import files to create phyloseq object
```{r}
# The otu table slot of phyloseq object 
TabTPM <- read.table(file.path("example_data/sample_TPM.tsv"),
                     header = TRUE, sep = "\t")
row.names(TabTPM) <- TabTPM$CDS_ID
TabTPM <- TabTPM[,-1]
TabTPM <- as.matrix.data.frame(TabTPM)

# The tax table slot of phyloseq object
Tabanno <- read.table(file.path("example_data/sample_annotation_classifications.tsv"),
                      header = TRUE, sep = "\t", na.strings = "<NA>")
rownames(Tabanno) <- Tabanno$CDS_ID
Tabanno <- Tabanno[,c(-1,-2)] # remove CDS_ID and KOID
Tabanno <- as.matrix.data.frame(Tabanno)

# The sample data slot of phyloseq object
samdf <- read.csv(file.path("example_data/Samdf.csv"))
rownames(samdf) <- samdf$SampleID

ps <- phyloseq(otu_table(TabTPM, taxa_are_rows = TRUE), 
               tax_table(Tabanno), sample_data(samdf))
ps # 20000 taxa and 4 samples
```

## Optional taxonomy level clean up
```{r}
# Define function to get the deepest taxa assignment level
RECps <- function(ps) {
  TaxTab2 <- as.data.frame(ps@tax_table)
  
  list.s = as.character(TaxTab2$Species)
  list.g = as.character(TaxTab2$Genus)
  list.f = as.character(TaxTab2$Family)
  list.o = as.character(TaxTab2$Order)
  list.c = as.character(TaxTab2$Class)
  list.p = as.character(TaxTab2$Phylum)
  list.k = as.character(TaxTab2$Kingdom)
  list.d = as.character(TaxTab2$Domain)
  list.REC = character(length(as.character(TaxTab2$Species)))
  
  for(i in 1:dim(TaxTab2)[1]){
    S = which(TaxTab2$Species[i] == "")
    G = which(TaxTab2$Genus[i] == "")
    F = which(TaxTab2$Family[i] == "")
    O = which(TaxTab2$Order[i] == "")
    C = which(TaxTab2$Class[i] == "")
    P = which(TaxTab2$Phylum[i] == "")
    K = which(TaxTab2$Kingdom[i] == "")
    D = which(TaxTab2$Domain[i] == "")
    if(length(S) == 0){
      list.REC[i] <- list.s[i]
    } else if(length(G) == 0){
      list.REC[i] <- list.g[i]
    } else if(length(F) == 0){
      list.REC[i] <- list.f[i]
    } else if(length(O) == 0){
      list.REC[i] <- list.o[i]
    } else if(length(C) == 0){
      list.REC[i] <- list.c[i]
    } else if(length(P) == 0){
      list.REC[i] <- list.p[i]
    } else if(length(K) == 0){
      list.REC[i] <- list.k[i]
    } else if(length(D) == 0){
      list.REC[i] <- list.d[i]
    } else
      list.REC[i] <- "meow"
  }
  
  TaxTab2$REC <- list.REC
  TaxTab2$REC <- factor(TaxTab2$REC)
  merge_phyloseq(ps, TaxTab2 %>% as.matrix() %>% tax_table())
}

ps.REC <- RECps(ps)
ps.REC # 20000 taxa and 4 samples 
```


## Heat map 
```{r}
# Define function to create heatmap per SampleID
IDHeat <- function(ps) {
  my_palette <- colorRampPalette(c("red", "yellow", "green"))(n = 299)
  # defines the color breaks manually for a "skewed" color transition
  col_breaks = c(seq(-1,0,length=100),      # for red
                 seq(0.01,0.8,length=100),  # for yellow
                 seq(0.81,1,length=100))    # for green

  ps <- ps %>% transform_sample_counts(function(x) x/sum(x) )  
  # Clean up the taxonomy 
  ps.glom <- ps %>% tax_glom(taxrank = "REC", NArm = FALSE)
  
  taxa.df <- psmelt(ps.glom)
  
  # REC level plot
  taxa.agg <- aggregate(Abundance ~ REC + SampleID,
                        data = taxa.df,
                        mean)
  taxa.cast <- dcast(taxa.agg, REC ~ SampleID, mean, value.var = "Abundance")
  
  # only plot the top 30 most abundant taxa 
  # need to change results from factor to numeric because of R
  row.names(taxa.cast) <- taxa.cast$REC
  taxa.cast <- taxa.cast[, -1]
  indx <- sapply(taxa.cast, is.factor)
  taxa.cast[indx] <- lapply(taxa.cast[indx], function(x) as.numeric(as.character(x))) 
  taxa.cast30 <- cbind(taxa.cast, total = rowSums(taxa.cast)) #  need numeric values
  taxa.cast30$taxa <- rownames(taxa.cast30)
  taxa.cast30 <- head(arrange(taxa.cast30,desc(total)), n = 30)
  row.names(taxa.cast30) <- taxa.cast30$taxa
  taxa.cast30 <- taxa.cast30[, -c(5,6)] # remove total and taxa name colums
  
  superheat(taxa.cast30,
            left.label.size = 1.2, 
            bottom.label.size = 0.1,
            order.rows = rev(order(rownames(taxa.cast30))),
            grid.hline = FALSE) 
}

IDHeat(ps.REC)
```



